# Generated by Django 2.1.1 on 2019-06-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=' ', editable=False, max_length=30, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
