# Generated by Django 2.1.1 on 2019-07-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='_', editable=False, max_length=30, verbose_name='Username'),
        ),
    ]
