# Generated by Django 2.1.1 on 2019-05-24 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.CharField(max_length=256)),
                ('branch', models.CharField(max_length=256)),
                ('pr', models.CharField(max_length=256)),
                ('ci_url', models.CharField(max_length=2048)),
                ('repo_url', models.CharField(max_length=2048)),
                ('comment', models.TextField(max_length=2500)),
                ('exec_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
