# Generated by Django 2.1.1 on 2019-05-30 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackswan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowexecution',
            old_name='comment',
            new_name='wf_str',
        ),
    ]
