# Generated by Django 2.1.1 on 2019-06-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackswan', '0003_auto_20190604_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='exec_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='state',
            field=models.CharField(default='running', max_length=256),
        ),
    ]
