# Generated by Django 2.1.1 on 2019-06-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackswan', '0004_auto_20190608_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='exec_number',
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='exec_number',
            field=models.IntegerField(default=0),
        ),
    ]
