# Generated by Django 2.1.1 on 2019-06-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackswan', '0005_auto_20190611_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowexecution',
            name='log',
            field=models.TextField(default='nan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='wf_json',
            field=models.TextField(default='nan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='wf_str',
            field=models.TextField(),
        ),
    ]
