# Generated by Django 2.1.1 on 2019-07-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackswan', '0006_auto_20190619_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='repo_url',
            field=models.CharField(default='NA', max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='NA', max_length=256),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='branch',
            field=models.CharField(default='NA', max_length=256),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='ci_url',
            field=models.CharField(default='NA', max_length=2048),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='log',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='pr',
            field=models.CharField(default='NA', max_length=256),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='revision',
            field=models.CharField(default='NA', max_length=256),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='wf_json',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='wf_str',
            field=models.TextField(default='NA'),
        ),
    ]
