# Generated by Django 2.1.1 on 2019-07-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackswan', '0007_auto_20190706_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.CharField(default='NA', max_length=256),
        ),
        migrations.AddField(
            model_name='project',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
