# Generated by Django 2.1.1 on 2019-07-16 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackswan', '0010_user_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='repo',
        ),
        migrations.RenameField(
            model_name='workflowexecution',
            old_name='username_pr',
            new_name='actor',
        ),
    ]
