# Generated by Django 2.1.1 on 2019-07-18 05:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackswan', '0012_project_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
