# Generated by Django 2.1.1 on 2019-07-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackswan', '0013_auto_20190718_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowexecution',
            name='wf_json',
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='artisan',
            field=models.FileField(default='NA', upload_to=''),
        ),
    ]
