# Generated by Django 2.2.4 on 2019-08-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackswan', '0014_auto_20190726_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(default='light-theme', max_length=30, verbose_name='Theme'),
        ),
    ]
